// Modals
export const OPEN_MODAL_FOR_CATEGORY_ADDITION = 'OPEN_MODAL_FOR_CATEGORY_ADDITION';

export const OPEN_MODAL_FOR_CATEGORY_EDITING = 'OPEN_MODAL_FOR_CATEGORY_EDITING';

export const OPEN_MODAL_FOR_CATEGORY_DELETING = 'OPEN_MODAL_FOR_CATEGORY_DELETING';

export const CLOSE_MODALS = 'CLOSE_MODALS';

// Filters
export const SET_SHOW_DONE_FILTER = 'SET_SHOW_DONE_FILTER';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';

// Categories
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const ADD_NESTED_CATEGORY = 'ADD_NESTED_CATEGORY';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const ADD_TASK = 'ADD_TASK';

export const TOGGLE_TASK = 'TOGGLE_TASK';

export const SAVE_EDITED_TASK_WITHOUT_TRANSFER = 'SAVE_EDITED_TASK_WITHOUT_TRANSFER';

export const SAVE_EDITED_TASK_WITH_TRANSFER = 'SAVE_EDITED_TASK_WITH_TRANSFER';
